version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: .ci/build-ci.sh
      - run: .ci/coverage.sh
      - store_test_results:
          path: coverage
      - run: .ci/build.sh

