version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: .ci/build-ci.sh
      - run: .ci/coverage.sh
      - codecov/upload:
          file: coverage
      - run: .ci/build.sh

