version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: .ci/build-ci.sh
      - run: .ci/coverage.sh
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: coverage
      - codecov/upload:
          file: coverage/clover.xml
      - run: .ci/build.sh

